# Generated by Django 4.2.1 on 2023-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_short_ctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='offer',
            field=models.CharField(default='Accepted', max_length=100),
        ),
    ]
